---
- name: Include install tasks
  ansible.builtin.include_tasks: install.yml

- name: Include configuration tasks
  ansible.builtin.include_tasks: configure.yml

- name: Include SSL tasks
  ansible.builtin.include_tasks: ssl.yml
  when: 
    - es_generate_certs == true

- name: Include upgrade tasks
  ansible.builtin.include_tasks: upgrade.yml
  when: es_upgrade == true