---
- name: Include install tasks
  ansible.builtin.include_tasks: install.yml

- name: Include configuration tasks
  ansible.builtin.include_tasks: configure.yml

- name: Include security tasks
  ansible.builtin.include_tasks: security.yml
  when: es_generate_certs == true

- name: Include upgrade tasks
  ansible.builtin.include_tasks: upgrade.yml
  when: es_upgrade == true